# Generated by Django 4.2.25 on 2025-11-10 18:35

import app_documentos.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONSTANCIA_HRS', 'Constancia de Horas'), ('CERT_CAP', 'Certificado de Capacitación'), ('ACREDITACION', 'Acreditación'), ('OTRO', 'Otro')], max_length=32)),
                ('titulo', models.CharField(max_length=160)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(upload_to=app_documentos.models.documento_upload_to)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('OBSERVADO', 'Observado'), ('APROBADO', 'Aprobado')], default='PENDIENTE', max_length=16)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
