# Generated by Django 4.2.25 on 2025-11-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('NOTA_INFORMATIVA', 'Nota Informativa'), ('SOL_CAP', 'Solicitud de Capacitación'), ('INVITACION', 'Invitación'), ('OFICIO', 'Oficio'), ('MEMO', 'Memorandum'), ('OTRO', 'Otro')], max_length=32),
        ),
    ]
