# Generated by Django 4.2.25 on 2025-11-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documentos', '0002_alter_documento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='fecha_documento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='usa_fecha_limite',
            field=models.BooleanField(default=False),
        ),
    ]
