# Generated by Django 4.2.25 on 2026-02-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documentos', '0003_documento_fecha_documento_documento_fecha_limite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='drive_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
