# Generated by Django 4.2.25 on 2025-11-03 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bombero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('grado', models.CharField(max_length=50)),
                ('nombres_apellidos', models.CharField(max_length=150)),
                ('horas_acumuladas', models.PositiveIntegerField(default=0)),
                ('emergencias_asistidas', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20)),
                ('horas', models.PositiveIntegerField()),
                ('emergencias', models.PositiveIntegerField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('bombero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.bombero')),
            ],
        ),
        migrations.CreateModel(
            name='CargaMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='cargas/')),
                ('mes', models.CharField(max_length=20)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
