# Generated by Django 4.2.25 on 2025-11-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargamensual',
            name='efectivos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cargamensual',
            name='total_horas',
            field=models.IntegerField(default=0),
        ),
    ]
