# Generated by Django 4.2.25 on 2025-11-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_cargamensual_efectivos_cargamensual_total_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargamensual',
            name='total_emergencias',
            field=models.IntegerField(default=0),
        ),
    ]
