# Generated by Django 4.2.25 on 2025-11-06 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_cargamensual_total_emergencias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargamensual',
            old_name='efectivos',
            new_name='efectivos_registrados',
        ),
    ]
