# Generated by Django 4.2.25 on 2025-11-08 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_rename_efectivos_cargamensual_efectivos_registrados'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20)),
                ('horas', models.PositiveIntegerField()),
                ('emergencias', models.PositiveIntegerField()),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('bombero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.bombero')),
            ],
        ),
    ]
